<a href="https://colab.research.google.com/github/archimehta/learning-pytorch/blob/main/tensor_math.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [3]:
import numpy as np

In [5]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])

In [6]:
# Addition
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [7]:
# Addition long-hand
torch.add(tensor_a, tensor_b)

tensor([ 6,  8, 10, 12])

In [8]:
# Subtraction
tensor_a - tensor_b

tensor([-4, -4, -4, -4])

In [9]:
tensor_b - tensor_a

tensor([4, 4, 4, 4])

In [11]:
# Another subtraction method
torch.sub(tensor_b, tensor_a)

tensor([4, 4, 4, 4])

In [12]:
# Multiplication
tensor_a * tensor_b

tensor([ 5, 12, 21, 32])

In [13]:
# Long hand
torch.multiply(tensor_a, tensor_b)

tensor([ 5, 12, 21, 32])

In [14]:
# Division
# Will convert to a float
tensor_b / tensor_a

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [15]:
torch.div(tensor_b, tensor_a)

tensor([5.0000, 3.0000, 2.3333, 2.0000])

In [16]:
# Remainder modulus
tensor_b % tensor_a

tensor([0, 0, 1, 0])

In [19]:
torch.remainder(tensor_b, tensor_a)

tensor([0, 0, 1, 0])

In [17]:
# Exponents/power
torch.pow(tensor_a, tensor_b)

tensor([    1,    64,  2187, 65536])

In [20]:
tensor_a.add(tensor_b)

tensor([ 6,  8, 10, 12])

In [21]:
# Reassignment
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [22]:
tensor_a

tensor([1, 2, 3, 4])

In [23]:
# tensor_a = tensor_a + tensor_b
tensor_a.add_(tensor_b)

tensor([ 6,  8, 10, 12])

In [24]:
tensor_a

tensor([ 6,  8, 10, 12])