<a href="https://colab.research.google.com/github/archimehta/learning-pytorch/blob/main/tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**TENSORS**


*   A torch. Tensor is a multidimensional matrix containing elements of a single data type
*   Similar to NumPy arrays, but work better on GPUs
*   Default data type is float-32
*   More suitable for deep learning than NumPy Array





In [1]:
import torch
import numpy as np

**LISTS**

In [3]:
my_list = [[1,2,3,4,5], [6,7,8,9,10]]
my_list

[[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]]

**NumPy Arrays**

In [9]:
np1 = np.random.rand(3,4)
np1

array([[0.38235051, 0.66043121, 0.24536267, 0.73601452],
       [0.81682626, 0.33043396, 0.8927229 , 0.80411546],
       [0.47530389, 0.00973076, 0.00591091, 0.27272197]])

In [7]:
np1.dtype

dtype('float64')

**Tensors**

In [14]:
tensor_2d = torch.randn(3,4)
tensor_2d
# tensor_2d.dtype

tensor([[ 0.9636, -1.4077, -0.3741, -0.0216],
        [ 0.8931, -1.8105, -1.0825, -1.1930],
        [-1.0368,  1.6159, -2.1458, -0.8293]])

In [11]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [12]:
# Create tensor out of NumPy array
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3824, 0.6604, 0.2454, 0.7360],
        [0.8168, 0.3304, 0.8927, 0.8041],
        [0.4753, 0.0097, 0.0059, 0.2727]], dtype=torch.float64)